[build-system]
requires = ["setuptools>=65", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ModifiedNEAT"
version = "0.6.0"
description = "Modified version of python NEAT algorithm that uses PyTorch modules"
readme = "README.md"
requires-python = ">=3.11"
authors = [
    {name = "Bradley Odimmasi", email = "bodimmasi@gmail.com"}
]
license = {text = "MIT"}
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Operating System :: OS Independent",
]

dependencies = [
    "numpy",
    "numba",
    "matplotlib",
    "tensorboard",
    "torch",
    "gymnasium",
    "pygame",
]

[project.optional-dependencies]
cpu = []
gpu = [
    "cuda-python",
    "cuda-toolkit",
    "numba-cuda[cu13]",
    "cupy-cuda11x; python_version < '3.12'",
    "cupy-cuda12x; python_version == '3.12'",
    "cupy-cuda13x; python_version >= '3.13'",
]
all = [
    "cuda-python",
    "cuda-toolkit",
    "numba-cuda[cu13]",
    "cupy-cuda11x; python_version < '3.12'",
    "cupy-cuda12x; python_version == '3.12'",
    "cupy-cuda13x; python_version >= '3.13'",
]

[project.urls]
Repository = "https://github.com/KshRaven/Modified-NEAT.git"
Issues = "https://github.com/KshRaven/Modified-NEAT/issues"

[tool.setuptools]
packages = [
    "ModifiedNEAT", 
    "ModifiedNEAT.base", 
    "ModifiedNEAT.base.cpu", 
    "ModifiedNEAT.base.cpu.functional", 
    "ModifiedNEAT.base.gpu", 
    "ModifiedNEAT.base.gpu.functional", 
    "ModifiedNEAT.config", 
    "ModifiedNEAT.cuda", 
    "ModifiedNEAT.cuda.functional", 
    "ModifiedNEAT.multproc", 
    "ModifiedNEAT.nn", 
    "ModifiedNEAT.nn.modules", 
    "ModifiedNEAT.optim", 
    "ModifiedNEAT.reporter", 
    "ModifiedNEAT.rl", 
    "ModifiedNEAT.util",
]
